title: "Jaewoo Shin"
name: "Jaewoo Shin"
description: "Personal portfolio, research notes, and study records in language models and efficient machine learning."
url: "https://jaewoo356.github.io"
baseurl: ""
repository: "jaewoo356/jaewoo356.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "air"
locale: "en-US"
timezone: "Asia/Seoul"

search: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: "Jaewoo Shin"
  avatar: "/assets/images/profile.jpg"
  bio: "Graduate student interested in Reasoning for LLMs."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jaewoo.shin@yonsei.ac.kr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaewoo356"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jae-woo-shin-4192591b8/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaewoo356"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jae-woo-shin-4192591b8/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

exclude:
  - .DS_Store
  - .sass-cache
  - .jekyll-cache
  - Gemfile.lock
  - node_modules
  - vendor
